//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessTracking.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessTracking.Localization.ProgramLocalization", typeof(ProgramLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black is playing.
        /// </summary>
        internal static string BlackPlaying {
            get {
                return ResourceManager.GetString("BlackPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black won.
        /// </summary>
        internal static string BlackWon {
            get {
                return ResourceManager.GetString("BlackWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-1.
        /// </summary>
        internal static string BlackWonRecord {
            get {
                return ResourceManager.GetString("BlackWonRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ––––––––––––––––––––––––.
        /// </summary>
        internal static string DashedLine {
            get {
                return ResourceManager.GetString("DashedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable otsu.
        /// </summary>
        internal static string DisableOtzu {
            get {
                return ResourceManager.GetString("DisableOtzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable otsu.
        /// </summary>
        internal static string EnableOtzu {
            get {
                return ResourceManager.GetString("EnableOtzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string FewSpaces {
            get {
                return ResourceManager.GetString("FewSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS: {0}.
        /// </summary>
        internal static string Fps {
            get {
                return ResourceManager.GetString("Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended.
        /// </summary>
        internal static string GameEnded {
            get {
                return ResourceManager.GetString("GameEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game loading failed.
        /// </summary>
        internal static string GameLoadingFailed {
            get {
                return ResourceManager.GetString("GameLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Recognized.
        /// </summary>
        internal static string GameRecognized {
            get {
                return ResourceManager.GetString("GameRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string GameRecordRow {
            get {
                return ResourceManager.GetString("GameRecordRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saved.
        /// </summary>
        internal static string GameSaved {
            get {
                return ResourceManager.GetString("GameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saving failed.
        /// </summary>
        internal static string GameSavingFailed {
            get {
                return ResourceManager.GetString("GameSavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid State.
        /// </summary>
        internal static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its a draw.
        /// </summary>
        internal static string ItsDraw {
            get {
                return ResourceManager.GetString("ItsDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2-1/2.
        /// </summary>
        internal static string ItsDrawRecord {
            get {
                return ResourceManager.GetString("ItsDrawRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} – {1}.
        /// </summary>
        internal static string LogRow {
            get {
                return ResourceManager.GetString("LogRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data arrived.
        /// </summary>
        internal static string NoDataArrived {
            get {
                return ResourceManager.GetString("NoDataArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalibration started, please wait.
        /// </summary>
        internal static string RecalibrationStarted {
            get {
                return ResourceManager.GetString("RecalibrationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene disrupted.
        /// </summary>
        internal static string SceneDisrupted {
            get {
                return ResourceManager.GetString("SceneDisrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default metric.
        /// </summary>
        internal static string SetDefaultMetric {
            get {
                return ResourceManager.GetString("SetDefaultMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set quadratic metric.
        /// </summary>
        internal static string SetQuadraticMetric {
            get {
                return ResourceManager.GetString("SetQuadraticMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of tracking was successful.
        /// </summary>
        internal static string StartOfTrackingSuccessful {
            get {
                return ResourceManager.GetString("StartOfTrackingSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking log – {0}.
        /// </summary>
        internal static string TimeCounter {
            get {
                return ResourceManager.GetString("TimeCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking calibration started, please wait.
        /// </summary>
        internal static string TrackingCalibrationStarted {
            get {
                return ResourceManager.GetString("TrackingCalibrationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking stoped.
        /// </summary>
        internal static string TrackingStopped {
            get {
                return ResourceManager.GetString("TrackingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected incoming message in {0}.
        /// </summary>
        internal static string UnexpectedIncomingMessage {
            get {
                return ResourceManager.GetString("UnexpectedIncomingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation State.
        /// </summary>
        internal static string ValidationState {
            get {
                return ResourceManager.GetString("ValidationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid State.
        /// </summary>
        internal static string ValidState {
            get {
                return ResourceManager.GetString("ValidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White is playing.
        /// </summary>
        internal static string WhitePlaying {
            get {
                return ResourceManager.GetString("WhitePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White won.
        /// </summary>
        internal static string WhiteWon {
            get {
                return ResourceManager.GetString("WhiteWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-0.
        /// </summary>
        internal static string WhiteWonRecord {
            get {
                return ResourceManager.GetString("WhiteWonRecord", resourceCulture);
            }
        }
    }
}
