var searchData=
[
  ['ichessboardlocalization',['IChessboardLocalization',['../interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_chessboard_localization.html',1,'ChessTracking::ImageProcessing::PipelineParts::StagesInterfaces']]],
  ['ichessboardlocalizationalgorithm',['IChessboardLocalizationAlgorithm',['../interface_chess_tracking_1_1_image_processing_1_1_chessboard_algorithms_1_1_i_chessboard_localization_algorithm.html',1,'ChessTracking::ImageProcessing::ChessboardAlgorithms']]],
  ['ifigureslocalization',['IFiguresLocalization',['../interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_figures_localization.html',1,'ChessTracking::ImageProcessing::PipelineParts::StagesInterfaces']]],
  ['ifigureslocalizationalgorithm',['IFiguresLocalizationAlgorithm',['../interface_chess_tracking_1_1_image_processing_1_1_figures_algorithms_1_1_i_figures_localization_algorithm.html',1,'ChessTracking::ImageProcessing::FiguresAlgorithms']]],
  ['ihanddetectionalgorithm',['IHandDetectionAlgorithm',['../interface_chess_tracking_1_1_image_processing_1_1_figures_algorithms_1_1_i_hand_detection_algorithm.html',1,'ChessTracking::ImageProcessing::FiguresAlgorithms']]],
  ['imagetobytearray',['ImageToByteArray',['../class_chess_tracking_1_1_utils_1_1_bitmap_extenstions.html#a92d1cea4ce86c497a45df4d600dda55e',1,'ChessTracking::Utils::BitmapExtenstions']]],
  ['initializecomponent',['InitializeComponent',['../class_chess_tracking_1_1_user_interface_1_1_advanced_settings_form.html#af97e63662ba24b5262a3c90140297020',1,'ChessTracking.UserInterface.AdvancedSettingsForm.InitializeComponent()'],['../class_chess_tracking_1_1_user_interface_1_1_calibration_snapshot_form.html#a84e93b5390fd2142c6eee5686b638a13',1,'ChessTracking.UserInterface.CalibrationSnapshotForm.InitializeComponent()'],['../class_chess_tracking_1_1_user_interface_1_1_main_game_form.html#a27ab4f2f64bddebc0ce3e9c566efccb0',1,'ChessTracking.UserInterface.MainGameForm.InitializeComponent()'],['../class_chess_tracking_1_1_user_interface_1_1_vizualization_form.html#a509b1e30f7e42828e98b0b4b874d7592',1,'ChessTracking.UserInterface.VizualizationForm.InitializeComponent()']]],
  ['initpipelinethread',['InitPipelineThread',['../class_chess_tracking_1_1_controlling_elements_1_1_tracking_manager.html#af0adf3ec805f8b8ce898fe6d7dfc77ff',1,'ChessTracking::ControllingElements::TrackingManager']]],
  ['inputdata',['InputData',['../class_chess_tracking_1_1_image_processing_1_1_pipeline_data_1_1_input_data.html',1,'ChessTracking::ImageProcessing::PipelineData']]],
  ['invalidstate',['InvalidState',['../class_chess_tracking_1_1_localization_1_1_program_localization.html#ad3531c309899fd497e8a48ca37c905ed',1,'ChessTracking::Localization::ProgramLocalization']]],
  ['iplanelocalization',['IPlaneLocalization',['../interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_plane_localization.html',1,'ChessTracking::ImageProcessing::PipelineParts::StagesInterfaces']]],
  ['iprogramstate',['IProgramState',['../interface_chess_tracking_1_1_controlling_elements_1_1_program_state_1_1_i_program_state.html',1,'ChessTracking::ControllingElements::ProgramState']]],
  ['irotatespacetochessboard',['IRotateSpaceToChessboard',['../interface_chess_tracking_1_1_image_processing_1_1_chessboard_algorithms_1_1_i_rotate_space_to_chessboard.html',1,'ChessTracking::ImageProcessing::ChessboardAlgorithms']]],
  ['isequivalent',['IsEquivalent',['../class_chess_tracking_1_1_game_1_1_chess_position.html#adf336b10f5e5943de1423fd93517cf48',1,'ChessTracking.Game.ChessPosition.IsEquivalent(ChessPosition other)'],['../class_chess_tracking_1_1_game_1_1_chess_position.html#ac4f8302f35f751eba3c9baa8a3ec43d0',1,'ChessTracking.Game.ChessPosition.IsEquivalent(ChessPosition lhs, ChessPosition rhs)'],['../class_chess_tracking_1_1_multithreading_messages_1_1_tracking_state.html#a27b9a526ddbbdfd93661e872b0be49c9',1,'ChessTracking.MultithreadingMessages.TrackingState.IsEquivalent()']]],
  ['isequivalentto',['IsEquivalentTo',['../class_chess_tracking_1_1_multithreading_messages_1_1_tracking_state.html#a6ee75ae80363cafcc7b00a26ddcbcf33',1,'ChessTracking::MultithreadingMessages::TrackingState']]],
  ['istracking',['IsTracking',['../class_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_general_1_1_pipeline.html#a86e9efc6c479c7a8137b19b80abd52d1',1,'ChessTracking::ImageProcessing::PipelineParts::General::Pipeline']]],
  ['isvalid',['IsValid',['../class_chess_tracking_1_1_game_1_1_chess_position.html#ad09d6fdc1fdd5c5652deaea5c246f0b9',1,'ChessTracking.Game.ChessPosition.IsValid()'],['../class_chess_tracking_1_1_game_1_1_chess_position.html#ad32aafa65d366856bc27b37565e0aff8',1,'ChessTracking.Game.ChessPosition.IsValid(int x, int y)']]],
  ['itsdraw',['ItsDraw',['../class_chess_tracking_1_1_localization_1_1_program_localization.html#a3aa0d5c5b46d20d843bf8339c3fce6cb',1,'ChessTracking::Localization::ProgramLocalization']]],
  ['itsdrawrecord',['ItsDrawRecord',['../class_chess_tracking_1_1_localization_1_1_program_localization.html#a0ddd784bfa8b1b850033f9cfcc1f0e13',1,'ChessTracking::Localization::ProgramLocalization']]]
];
