namespace ChessTracking.ImageProcessing.PipelineData
{
    /// <summary>
    /// Data generated by chessboard detection
    /// </summary>
    class ChessboardTrackingData
    {
        public double FieldSize { get; set; }
    }
}
