using System.Drawing;
using Emgu.CV.Structure;

namespace ChessTracking.ImageProcessing.PipelineData
{
    /// <summary>
    /// Data generated by plane detection
    /// </summary>
    class PlaneTrackingData
    {
        public Emgu.CV.Image<Rgb, byte> MaskedColorImageOfTable { get; set; }
        public byte[] CannyDepthData { get; set; }
        public Bitmap ColorBitmap { get; set; }
        public bool[] MaskOfTable { get; set; }
    }
}
