var namespace_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces =
[
    [ "IChessboardLocalization", "interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_chessboard_localization.html", "interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_chessboard_localization" ],
    [ "IFiguresLocalization", "interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_figures_localization.html", "interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_figures_localization" ],
    [ "IPlaneLocalization", "interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_plane_localization.html", "interface_chess_tracking_1_1_image_processing_1_1_pipeline_parts_1_1_stages_interfaces_1_1_i_plane_localization" ]
];